export const coffeesData = [
  {
    id: 1,
    name: 'Expresso tradicional',
    category: ['Tradicional'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    image: 'expresso-tradicional',
  },
  {
    id: 2,
    name: 'Expresso Americano',
    category: ['Tradicional'],
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
    image: 'expresso-americano',
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    category: ['Tradicional'],
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
    image: 'expresso-cremoso',
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    category: ['Tradicional'],
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    image: 'expresso-gelado',
  },
  {
    id: 5,
    name: 'Café com Leite',
    category: ['Tradicional', 'Com leite'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
    image: 'cafe-com-leite',
  },
  {
    id: 6,
    name: 'Latte',
    category: ['Tradicional'],
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
    image: 'latte',
  },
  {
    id: 7,
    name: 'Capuccino',
    category: ['Tradicional'],
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
    image: 'capuccino',
  },
  {
    id: 8,
    name: 'Macchiato',
    category: ['Tradicional'],
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
    image: 'macchiato',
  },
  {
    id: 9,
    name: 'Mocaccino',
    category: ['Tradicional'],
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    image: 'mocaccino',
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    category: ['Tradicional'],
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    image: 'chocolate-quente',
  },
  {
    id: 11,
    name: 'Cubano',
    category: ['Tradicional'],
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    image: 'cubano',
  },
  {
    id: 12,
    name: 'Havaiano',
    category: ['Tradicional'],
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    image: 'havaiano',
  },
  {
    id: 13,
    name: 'Árabe',
    category: ['Tradicional'],
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    image: 'arabe',
  },
  {
    id: 14,
    name: 'Irlandês',
    category: ['Tradicional'],
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    image: 'irlandes',
  },
]
